name: Auto Update TV Malaysia

on:
  schedule:
    - cron: '0 */2 * * *' # Berjalan secara automatik setiap 2 jam
  workflow_dispatch:      # Membenarkan anda menekan butang "Run workflow" secara manual

permissions:
  contents: write         # Wajib: Memberi kebenaran untuk robot menyimpan fail ke repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run grabber script
        run: python grabber.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Memadam fail lama playlist.m3u jika ada (pilihan)
          rm -f playlist.m3u
          
          # Menambah fail baru dengan nama TV Malaysia.m3u
          # Penggunaan tanda petikan " " adalah wajib kerana nama fail ada jarak
          git add "TV Malaysia.m3u"
          
          # Melakukan commit hanya jika ada perubahan
          git commit -m "Auto Update: $(date)" || exit 0
          git push
